server:
  port: 8000

spring:
  application:
    name: arena

logging:
  file:
    name: /logs/app.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
