server:
  port: 8003
spring:
  application:
    name: ui

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: /logs/app.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

