spring:
  application:
    name: camp
  data:
    rest:
      basePath: /spring-rest-hateoas

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: /logs/app.log

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
